app:
  security:
    cert:
      path: public.cer
      type: X.509
      provider: BC
    keyStore:
      path: private.p12
      type: PKCS12
      password: password
    sign:
      alg: SHA256withRSA